# Generated by Django 2.1.2 on 2021-01-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('book', models.ManyToManyField(to='app01.Book')),
            ],
        ),
    ]
